baseURL = "https://bwarren2.github.io/voting_2016/"
languageCode = "en-us"
title = "Understanding the 2016 Presidential Election"
theme = "tale-hugo"
canonifyurls = true
author = "Ben"
googleAnalytics = "UA-124735498-2"

[Author]
    name = "Ben"
[Params]
    css = ["css/custom.css"]
